<User>:
    BoxLayout:
        orientation: "vertical"

        Label:
            id: name_username
            text: "ID: "
            font_size: 20
            size_hint_y: 0.2
        Label:
            id: name_password
            text: "pass: "
            font_size: 20
            size_hint_y: 0.2
        Label:
            id: email
            text: "email: "
            font_size: 20
            size_hint_y: 0.2